### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by JunJie00000** [kxvxnc/Stockx-Discord-Bot#5]
![image](https://user-images.githubusercontent.com/50447897/108343331-c717ba00-7216-11eb-8de8-c658e0ab7e8d.png)
Bot dont work anymore as there is a KeyError

**Comment by xenonstery** [comment]
i'm having key error problem same as jun jie 00000

**Comment by RuthlessKoncept** [comment]
I managed to figure this out. It's the x-algolia-api-key that's causing the issue.

If you replace it with 6b5e76b49705eb9f51a06d3c82f7acee, you'll find the bot working again.

**Comment by JunJie00000** [comment]
> I managed to figure this out. It's the x-algolia-api-key that's causing the issue.
> 
> If you replace it with 6b5e76b49705eb9f51a06d3c82f7acee, you'll find the bot working again.

solved! thanks alot!

**Comment by xenonstery** [comment]
thanks alot

**Comment by not-baro** [comment]
i'm getting TypeError: __new__() got an unexpected keyword argument 'deny_new'

**Comment by ixacc** [comment]
> i'm getting TypeError: **new**() got an unexpected keyword argument 'deny_new'

I also got this problem, any fix?

**Comment by RuthlessKoncept** [comment]
> 
> 
> i'm getting TypeError: **new**() got an unexpected keyword argument 'deny_new'

I've had this pop up a few times whilst messing around with it. Do you have the latest Discord.py? This will likely solve the issue.

Use python -m pip install -U discord.py or python3 -m pip install -U discord.py and once it's done, reload this script and you should be up and running again.

**Comment by RuthlessKoncept** [comment]
> 
> 
> > i'm getting TypeError: **new**() got an unexpected keyword argument 'deny_new'
> 
> I also got this problem, any fix?

See my above post.

**Comment by not-baro** [comment]
> > > i'm getting TypeError: **new**() got an unexpected keyword argument 'deny_new'
> > 
> > 
> > I also got this problem, any fix?
> 
> See my above post.

i updated discord.py , the bot seemed to be started. But when i do .sx i get this on script's side:  InsecureRequestWarning: Unverified HTTPS request is being made to host 'xw7sbct9v6-dsn.algolia.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

what should i do?

**Comment by RuthlessKoncept** [comment]
> 
> 
> > > > i'm getting TypeError: **new**() got an unexpected keyword argument 'deny_new'
> > > 
> > > 
> > > I also got this problem, any fix?
> > 
> > 
> > See my above post.
> 
> i updated discord.py , the bot seemed to be started. But when i do .sx i get this on script's side: InsecureRequestWarning: Unverified HTTPS request is being made to host 'xw7sbct9v6-dsn.algolia.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
> 
> what should i do?

It doesn't stop the bot from working, it's just that the connection to algolia is unsecured. Since you are only sending keywords or style codes, I didn't see this as an issue to concern myself about.

If you use the link, it tells you how to either disable the warning, or to ask for a certificate. 3rd option is just to keep ignoring it.

**Comment by not-baro** [comment]
> > > > > i'm getting TypeError: **new**() got an unexpected keyword argument 'deny_new'
> > > > 
> > > > 
> > > > I also got this problem, any fix?
> > > 
> > > 
> > > See my above post.
> > 
> > 
> > i updated discord.py , the bot seemed to be started. But when i do .sx i get this on script's side: InsecureRequestWarning: Unverified HTTPS request is being made to host 'xw7sbct9v6-dsn.algolia.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
> > what should i do?
> 
> It doesn't stop the bot from working, it's just that the connection to algolia is unsecured. Since you are only sending keywords or style codes, I didn't see this as an issue to concern myself about.
> 
> If you use the link, it tells you how to either disable the warning, or to ask for a certificate. 3rd option is just to keep ignoring it.

yeah but the bot is actually sending nothing back

**Comment by not-baro** [comment]
because this warning raises an exception:  InsecureRequestWarning: Unverified HTTPS request is being made to host 'xw7sbct9v6-dsn.algolia.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Ignoring exception in command sx:
Traceback (most recent call last):
  File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 99, in sx
    numResults = len(r.json()["hits"])
KeyError: 'hits'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'hits'

**Comment by RuthlessKoncept** [comment]
> 
> 
> because this warning raises an exception: InsecureRequestWarning: Unverified HTTPS request is being made to host 'xw7sbct9v6-dsn.algolia.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
> warnings.warn(
> Ignoring exception in command sx:
> Traceback (most recent call last):
> File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
> ret = await coro(*args, **kwargs)
> File "main.py", line 99, in sx
> numResults = len(r.json()["hits"])
> KeyError: 'hits'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
> await ctx.command.invoke(ctx)
> File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
> await injected(*ctx.args, **ctx.kwargs)
> File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
> raise CommandInvokeError(exc) from exc
> discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'hits'

Ah. If you scroll up in this chain, have you seen my post about the new API key?

Try that and reboot the script.

**Comment by not-baro** [comment]
i tried bro, but same error

**Comment by not-baro** [comment]
> > because this warning raises an exception: InsecureRequestWarning: Unverified HTTPS request is being made to host 'xw7sbct9v6-dsn.algolia.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
> > warnings.warn(
> > Ignoring exception in command sx:
> > Traceback (most recent call last):
> > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
> > ret = await coro(*args, **kwargs)
> > File "main.py", line 99, in sx
> > numResults = len(r.json()["hits"])
> > KeyError: 'hits'
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last):
> > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
> > await ctx.command.invoke(ctx)
> > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
> > await injected(*ctx.args, **ctx.kwargs)
> > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
> > raise CommandInvokeError(exc) from exc
> > discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'hits'
> 
> Ah. If you scroll up in this chain, have you seen my post about the new API key?
> 
> Try that and reboot the script.

i tried bro, same error

**Comment by RuthlessKoncept** [comment]
> 
> 
> > > because this warning raises an exception: InsecureRequestWarning: Unverified HTTPS request is being made to host 'xw7sbct9v6-dsn.algolia.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
> > > warnings.warn(
> > > Ignoring exception in command sx:
> > > Traceback (most recent call last):
> > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
> > > ret = await coro(*args, **kwargs)
> > > File "main.py", line 99, in sx
> > > numResults = len(r.json()["hits"])
> > > KeyError: 'hits'
> > > The above exception was the direct cause of the following exception:
> > > Traceback (most recent call last):
> > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
> > > await ctx.command.invoke(ctx)
> > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
> > > await injected(*ctx.args, **ctx.kwargs)
> > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
> > > raise CommandInvokeError(exc) from exc
> > > discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'hits'
> > 
> > 
> > Ah. If you scroll up in this chain, have you seen my post about the new API key?
> > Try that and reboot the script.
> 
> i tried bro, same error

Huh. If you can send me your .py file without the discord token, I can take a look.

**Comment by ixacc** [comment]
> > > > because this warning raises an exception: InsecureRequestWarning: Unverified HTTPS request is being made to host 'xw7sbct9v6-dsn.algolia.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
> > > > warnings.warn(
> > > > Ignoring exception in command sx:
> > > > Traceback (most recent call last):
> > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
> > > > ret = await coro(*args, **kwargs)
> > > > File "main.py", line 99, in sx
> > > > numResults = len(r.json()["hits"])
> > > > KeyError: 'hits'
> > > > The above exception was the direct cause of the following exception:
> > > > Traceback (most recent call last):
> > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
> > > > await ctx.command.invoke(ctx)
> > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
> > > > await injected(*ctx.args, **ctx.kwargs)
> > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
> > > > raise CommandInvokeError(exc) from exc
> > > > discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'hits'
> > > 
> > > 
> > > Ah. If you scroll up in this chain, have you seen my post about the new API key?
> > > Try that and reboot the script.
> > 
> > 
> > i tried bro, same error
> 
> Huh. If you can send me your .py file without the discord token, I can take a look. Or post it into a pastebin or something.
> 
> _edit_ - Mine is currently working so without seeing your specific .py I can't offer much else atm.

I got the bot running now but i have the same error as above, can i send you my .py?

**Comment by not-baro** [comment]
> > > > > because this warning raises an exception: InsecureRequestWarning: Unverified HTTPS request is being made to host 'xw7sbct9v6-dsn.algolia.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
> > > > > warnings.warn(
> > > > > Ignoring exception in command sx:
> > > > > Traceback (most recent call last):
> > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
> > > > > ret = await coro(*args, **kwargs)
> > > > > File "main.py", line 99, in sx
> > > > > numResults = len(r.json()["hits"])
> > > > > KeyError: 'hits'
> > > > > The above exception was the direct cause of the following exception:
> > > > > Traceback (most recent call last):
> > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
> > > > > await ctx.command.invoke(ctx)
> > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
> > > > > await injected(*ctx.args, **ctx.kwargs)
> > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
> > > > > raise CommandInvokeError(exc) from exc
> > > > > discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'hits'
> > > > 
> > > > 
> > > > Ah. If you scroll up in this chain, have you seen my post about the new API key?
> > > > Try that and reboot the script.
> > > 
> > > 
> > > i tried bro, same error
> > 
> > 
> > Huh. If you can send me your .py file without the discord token, I can take a look. Or post it into a pastebin or something.
> > _edit_ - Mine is currently working so without seeing your specific .py I can't offer much else atm.
> 
> I got the bot running now but i have the same error as above, can i send you my .py?

sure bro: https://pastebin.com/pTU36xjz

**Comment by RuthlessKoncept** [comment]
> 
> 
> > > > > because this warning raises an exception: InsecureRequestWarning: Unverified HTTPS request is being made to host 'xw7sbct9v6-dsn.algolia.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
> > > > > warnings.warn(
> > > > > Ignoring exception in command sx:
> > > > > Traceback (most recent call last):
> > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
> > > > > ret = await coro(*args, **kwargs)
> > > > > File "main.py", line 99, in sx
> > > > > numResults = len(r.json()["hits"])
> > > > > KeyError: 'hits'
> > > > > The above exception was the direct cause of the following exception:
> > > > > Traceback (most recent call last):
> > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
> > > > > await ctx.command.invoke(ctx)
> > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
> > > > > await injected(*ctx.args, **ctx.kwargs)
> > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
> > > > > raise CommandInvokeError(exc) from exc
> > > > > discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'hits'
> > > > 
> > > > 
> > > > Ah. If you scroll up in this chain, have you seen my post about the new API key?
> > > > Try that and reboot the script.
> > > 
> > > 
> > > i tried bro, same error
> > 
> > 
> > Huh. If you can send me your .py file without the discord token, I can take a look. Or post it into a pastebin or something.
> > _edit_ - Mine is currently working so without seeing your specific .py I can't offer much else atm.
> 
> I got the bot running now but i have the same error as above, can i send you my .py?

Sure, just upload it somewhere or copy the code (without the discord token) onto pastebin.

**Comment by ixacc** [comment]
> > > > > > because this warning raises an exception: InsecureRequestWarning: Unverified HTTPS request is being made to host 'xw7sbct9v6-dsn.algolia.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
> > > > > > warnings.warn(
> > > > > > Ignoring exception in command sx:
> > > > > > Traceback (most recent call last):
> > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
> > > > > > ret = await coro(*args, **kwargs)
> > > > > > File "main.py", line 99, in sx
> > > > > > numResults = len(r.json()["hits"])
> > > > > > KeyError: 'hits'
> > > > > > The above exception was the direct cause of the following exception:
> > > > > > Traceback (most recent call last):
> > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
> > > > > > await ctx.command.invoke(ctx)
> > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
> > > > > > await injected(*ctx.args, **ctx.kwargs)
> > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
> > > > > > raise CommandInvokeError(exc) from exc
> > > > > > discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'hits'
> > > > > 
> > > > > 
> > > > > Ah. If you scroll up in this chain, have you seen my post about the new API key?
> > > > > Try that and reboot the script.
> > > > 
> > > > 
> > > > i tried bro, same error
> > > 
> > > 
> > > Huh. If you can send me your .py file without the discord token, I can take a look. Or post it into a pastebin or something.
> > > _edit_ - Mine is currently working so without seeing your specific .py I can't offer much else atm.
> > 
> > 
> > I got the bot running now but i have the same error as above, can i send you my .py?
> 
> Sure, just upload it somewhere or copy the code (without the discord token) onto pastebin.

https://pastebin.com/h6FpUc6P

**Comment by RuthlessKoncept** [comment]
> 
> 
> > > > > > because this warning raises an exception: InsecureRequestWarning: Unverified HTTPS request is being made to host 'xw7sbct9v6-dsn.algolia.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
> > > > > > warnings.warn(
> > > > > > Ignoring exception in command sx:
> > > > > > Traceback (most recent call last):
> > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
> > > > > > ret = await coro(*args, **kwargs)
> > > > > > File "main.py", line 99, in sx
> > > > > > numResults = len(r.json()["hits"])
> > > > > > KeyError: 'hits'
> > > > > > The above exception was the direct cause of the following exception:
> > > > > > Traceback (most recent call last):
> > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
> > > > > > await ctx.command.invoke(ctx)
> > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
> > > > > > await injected(*ctx.args, **ctx.kwargs)
> > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
> > > > > > raise CommandInvokeError(exc) from exc
> > > > > > discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'hits'
> > > > > 
> > > > > 
> > > > > Ah. If you scroll up in this chain, have you seen my post about the new API key?
> > > > > Try that and reboot the script.
> > > > 
> > > > 
> > > > i tried bro, same error
> > > 
> > > 
> > > Huh. If you can send me your .py file without the discord token, I can take a look. Or post it into a pastebin or something.
> > > _edit_ - Mine is currently working so without seeing your specific .py I can't offer much else atm.
> > 
> > 
> > I got the bot running now but i have the same error as above, can i send you my .py?
> 
> sure bro: https://pastebin.com/pTU36xjz

Ok, this is pretty simple.

If you scroll towards the bottom, there is another API key that you haven't changed to the new one. Flip that to the new one as well and it works. 

**https://pastebin.com/0Zk5tL6r** if you would like to just copy it with the amendment.

**Comment by RuthlessKoncept** [comment]
> 
> 
> > > > > > > because this warning raises an exception: InsecureRequestWarning: Unverified HTTPS request is being made to host 'xw7sbct9v6-dsn.algolia.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
> > > > > > > warnings.warn(
> > > > > > > Ignoring exception in command sx:
> > > > > > > Traceback (most recent call last):
> > > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
> > > > > > > ret = await coro(*args, **kwargs)
> > > > > > > File "main.py", line 99, in sx
> > > > > > > numResults = len(r.json()["hits"])
> > > > > > > KeyError: 'hits'
> > > > > > > The above exception was the direct cause of the following exception:
> > > > > > > Traceback (most recent call last):
> > > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
> > > > > > > await ctx.command.invoke(ctx)
> > > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
> > > > > > > await injected(*ctx.args, **ctx.kwargs)
> > > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
> > > > > > > raise CommandInvokeError(exc) from exc
> > > > > > > discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'hits'
> > > > > > 
> > > > > > 
> > > > > > Ah. If you scroll up in this chain, have you seen my post about the new API key?
> > > > > > Try that and reboot the script.
> > > > > 
> > > > > 
> > > > > i tried bro, same error
> > > > 
> > > > 
> > > > Huh. If you can send me your .py file without the discord token, I can take a look. Or post it into a pastebin or something.
> > > > _edit_ - Mine is currently working so without seeing your specific .py I can't offer much else atm.
> > > 
> > > 
> > > I got the bot running now but i have the same error as above, can i send you my .py?
> > 
> > 
> > Sure, just upload it somewhere or copy the code (without the discord token) onto pastebin.
> 
> https://pastebin.com/h6FpUc6P

Same issue as the other one. 

**https://pastebin.com/0Zk5tL6r** copy that and insert your discord token, should run fine.

**Comment by ixacc** [comment]
> > > > > > > > because this warning raises an exception: InsecureRequestWarning: Unverified HTTPS request is being made to host 'xw7sbct9v6-dsn.algolia.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
> > > > > > > > warnings.warn(
> > > > > > > > Ignoring exception in command sx:
> > > > > > > > Traceback (most recent call last):
> > > > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
> > > > > > > > ret = await coro(*args, **kwargs)
> > > > > > > > File "main.py", line 99, in sx
> > > > > > > > numResults = len(r.json()["hits"])
> > > > > > > > KeyError: 'hits'
> > > > > > > > The above exception was the direct cause of the following exception:
> > > > > > > > Traceback (most recent call last):
> > > > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
> > > > > > > > await ctx.command.invoke(ctx)
> > > > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
> > > > > > > > await injected(*ctx.args, **ctx.kwargs)
> > > > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
> > > > > > > > raise CommandInvokeError(exc) from exc
> > > > > > > > discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'hits'
> > > > > > > 
> > > > > > > 
> > > > > > > Ah. If you scroll up in this chain, have you seen my post about the new API key?
> > > > > > > Try that and reboot the script.
> > > > > > 
> > > > > > 
> > > > > > i tried bro, same error
> > > > > 
> > > > > 
> > > > > Huh. If you can send me your .py file without the discord token, I can take a look. Or post it into a pastebin or something.
> > > > > _edit_ - Mine is currently working so without seeing your specific .py I can't offer much else atm.
> > > > 
> > > > 
> > > > I got the bot running now but i have the same error as above, can i send you my .py?
> > > 
> > > 
> > > Sure, just upload it somewhere or copy the code (without the discord token) onto pastebin.
> > 
> > 
> > https://pastebin.com/h6FpUc6P
> 
> Same issue as the other one.
> 
> **https://pastebin.com/0Zk5tL6r** copy that and insert your discord token, should run fine.

this worked! Thank you very much :)

**Comment by RuthlessKoncept** [comment]
> 
> 
> > > > > > > > > because this warning raises an exception: InsecureRequestWarning: Unverified HTTPS request is being made to host 'xw7sbct9v6-dsn.algolia.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
> > > > > > > > > warnings.warn(
> > > > > > > > > Ignoring exception in command sx:
> > > > > > > > > Traceback (most recent call last):
> > > > > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
> > > > > > > > > ret = await coro(*args, **kwargs)
> > > > > > > > > File "main.py", line 99, in sx
> > > > > > > > > numResults = len(r.json()["hits"])
> > > > > > > > > KeyError: 'hits'
> > > > > > > > > The above exception was the direct cause of the following exception:
> > > > > > > > > Traceback (most recent call last):
> > > > > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
> > > > > > > > > await ctx.command.invoke(ctx)
> > > > > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
> > > > > > > > > await injected(*ctx.args, **ctx.kwargs)
> > > > > > > > > File "C:\Users\MioPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
> > > > > > > > > raise CommandInvokeError(exc) from exc
> > > > > > > > > discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'hits'
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Ah. If you scroll up in this chain, have you seen my post about the new API key?
> > > > > > > > Try that and reboot the script.
> > > > > > > 
> > > > > > > 
> > > > > > > i tried bro, same error
> > > > > > 
> > > > > > 
> > > > > > Huh. If you can send me your .py file without the discord token, I can take a look. Or post it into a pastebin or something.
> > > > > > _edit_ - Mine is currently working so without seeing your specific .py I can't offer much else atm.
> > > > > 
> > > > > 
> > > > > I got the bot running now but i have the same error as above, can i send you my .py?
> > > > 
> > > > 
> > > > Sure, just upload it somewhere or copy the code (without the discord token) onto pastebin.
> > > 
> > > 
> > > https://pastebin.com/h6FpUc6P
> > 
> > 
> > Same issue as the other one.
> > **https://pastebin.com/0Zk5tL6r** copy that and insert your discord token, should run fine.
> 
> this worked! Thank you very much :)

Glad I could help!

**Comment by not-baro** [comment]
Works fine now thankyou

**Comment by adityasanehi** [comment]
Hey, how do i make a new API key?

**Comment by adityasanehi** [comment]
https://i.imgur.com/0RWXejt.png i'm getting this error

**Comment by adityasanehi** [comment]
> > i'm getting TypeError: **new**() got an unexpected keyword argument 'deny_new'
> 
> I've had this pop up a few times whilst messing around with it. Do you have the latest Discord.py? This will likely solve the issue.
> 
> Use python -m pip install -U discord.py or python3 -m pip install -U discord.py and once it's done, reload this script and you should be up and running again.
> 
> Apologies for the late response. I'm hopeful this should fix it for you.

Hey, sorry to bother you but I’m facing a very similar problem w his GOAT price checker, it cannot parse the json file (JSONDecodeError). Could you have a look, does it require changing headers as well, or something else. Thankyou.

**Comment by adityasanehi** [comment]
Also, this seems to not run and give that deny_new error when put on heroku. Any specefic reason?

**Comment by RuthlessKoncept** [comment]
> > > i'm getting TypeError: **new**() got an unexpected keyword argument 'deny_new'
> > 
> > 
> > I've had this pop up a few times whilst messing around with it. Do you have the latest Discord.py? This will likely solve the issue.
> > Use python -m pip install -U discord.py or python3 -m pip install -U discord.py and once it's done, reload this script and you should be up and running again.
> > Apologies for the late response. I'm hopeful this should fix it for you.
> 
> Hey, sorry to bother you but I’m facing a very similar problem w his GOAT price checker, it cannot parse the json file (JSONDecodeError). Could you have a look, does it require changing headers/API-keys as well, or something else? Thankyou.

Mine was broken too. If you go to line 105 and change it to : "Algolia for JavaScript (4.8.4); Browser"      -  It seems to work. I didn't change the one at line 24 but it seems to be fine for now. I'll keep an eye out.

**Comment by adityasanehi** [comment]
> 
> 
> > > > i'm getting TypeError: **new**() got an unexpected keyword argument 'deny_new'
> > > 
> > > 
> > > I've had this pop up a few times whilst messing around with it. Do you have the latest Discord.py? This will likely solve the issue.
> > > Use python -m pip install -U discord.py or python3 -m pip install -U discord.py and once it's done, reload this script and you should be up and running again.
> > > Apologies for the late response. I'm hopeful this should fix it for you.
> > 
> > 
> > Hey, sorry to bother you but I’m facing a very similar problem w his GOAT price checker, it cannot parse the json file (JSONDecodeError). Could you have a look, does it require changing headers/API-keys as well, or something else? Thankyou.
> 
> Edit : Ok, mine is still broken on some shoes. I'll take a look later.

Opal is still accessing the same search API and API-key and it works for them.

**Comment by RuthlessKoncept** [comment]
> > > > > i'm getting TypeError: **new**() got an unexpected keyword argument 'deny_new'
> > > > 
> > > > 
> > > > I've had this pop up a few times whilst messing around with it. Do you have the latest Discord.py? This will likely solve the issue.
> > > > Use python -m pip install -U discord.py or python3 -m pip install -U discord.py and once it's done, reload this script and you should be up and running again.
> > > > Apologies for the late response. I'm hopeful this should fix it for you.
> > > 
> > > 
> > > Hey, sorry to bother you but I’m facing a very similar problem w his GOAT price checker, it cannot parse the json file (JSONDecodeError). Could you have a look, does it require changing headers/API-keys as well, or something else? Thankyou.
> > 
> > 
> > Edit : Ok, mine is still broken on some shoes. I'll take a look later.
> 
> Opal is still accessing the same search API and API-key and it works for them. They still use the same headers.

I edited just after you commented. Take those steps and let me know what happens.

**Comment by adityasanehi** [comment]
Made this change, trying now. https://imgur.com/N17iCZf

**Comment by RuthlessKoncept** [comment]
> Made this change, trying now. https://imgur.com/N17iCZf

add me on discord : Koncept#4199 and I can provide better assistance
