### ISSUE TITLE
can't retrieve any information 

### ISSUE THREAD

**Issue by JunJie00000** [kxvxnc/Stockx-Discord-Bot#6]
![unknown](https://user-images.githubusercontent.com/50447897/117834500-c89ece80-b2a9-11eb-858d-18a514e77303.png)

**Comment by adityasanehi** [comment]
Same error, did you find a solution yet?

**Comment by RuthlessKoncept** [comment]
I've just forked this and edited main.py with the fix. Click forks in the top right, or click on my name.

**Comment by adityasanehi** [comment]
How do I make a new API token if the current one expires. Haven't used Algolia.

**Comment by RuthlessKoncept** [comment]
I've had mine running on the same token for around 10 days now and it still works. Until it kicks the bucket, I can't tell you.

**Comment by adityasanehi** [comment]
Ah okay.
